### ISSUE TITLE
Cannot get output

### ISSUE THREAD

**Issue by cristiadu** [ytanikin/pr-conventional-commits#14]
I was trying to get the output from STDOUT to send as a message on the PR, but the `steps.ID.outputs.stdout` variable is not populated by this workflow, in fact none of the `outputs` have anything on them when I look for it.

```yaml
name: PR Conventional Commit Validation

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        id: validation
        continue-on-error: true
        uses: ytanikin/PRConventionalCommits@1.1.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert", "sync", "feature", "cicd", "bugfix"]'
      - name: Send Status Message
        if: ${{ steps.validation.outcome != 'success' }}
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const message = `PR Conventional Commit Validation: ${{ toJSON(steps.validation.outputs) }}`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
```

it will just output as `{}` on the message.
