### ISSUE TITLE
Error: Invalid or missing task type: '' for Draft PRs

### ISSUE THREAD

**Issue by luber** [ytanikin/pr-conventional-commits#23]
Hi,
We have created a Draft PR with next title: `feat: 1234 test pr title, part 1`
and it fail to validate.

```
Run ytanikin/PRConventionalCommits@1.2.0
  with:
    task_types: ["feat","fix","docs","test","ci","refactor","perf","chore","revert"]
    add_label: true
    token: ***
Error: Invalid or missing task type: ''. Must be one of: feat, fix, docs, test, ci, refactor, perf, chore, revert
Current labels: []
Task types: ["feat","fix","docs","test","ci","refactor","perf","chore","revert"]
Custom labels: {}
Managed labels: [
  'feat',
  'fix',
  'docs',
  'test',
  'ci',
  'refactor',
  'perf',
  'chore',
  'revert',
  'breaking change'
]
Error: Cannot read properties of undefined (reading 'type')
```

The workflow is:
```
name: PR Conventional Commit Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  pull-requests: write
  contents: read

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses:  ytanikin/PRConventionalCommits@1.2.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
```
