### ISSUE TITLE
Error: Unable to resolve action. Repository not found: ytanikin/PRConventionalCommits

### ISSUE THREAD

**Issue by alexb-uk** [ytanikin/pr-conventional-commits#29]
Hi,

Firstly thank you very much for this handy action script 👍 

Our workflows suddenly started failing this morning with the following error:
```
Error: Unable to resolve action. Repository not found: ytanikin/PRConventionalCommits
```

They had been working perfectly for many weeks / months.

After some digging [I found a discussion](https://github.com/orgs/community/discussions/59086) from two years ago that said GitHub doesn't support URL redirects in action script names. This is obviously not 100% true HOWEVER removing the redirect did immediately fix our builds. Maybe GitHub caches the redirect and if it fails on the cache miss store the "Not Found" error for a long time.

## Workaround / Fix
Rename script to match repo url:
```yaml
jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses:  ytanikin/PRConventionalCommits@x.y.z
```
becomes
```yaml
jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses:  ytanikin/pr-conventional-commits@x.y.z
```

I would suggest changing the examples from `ytanikin/PRConventionalCommits@1.1.0` to `ytanikin/pr-conventional-commits@1.3.0` which appears to work perfectly.
